spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hbm2ddl_auto: create
  devtools:
    restart:
      exclude: static/**,public/**
      livereload: enabled